# makefile based on scott mcpeak's grad school page :)
# 	http://scottmcpeak.com/autodepend/autodepend.html
# [which actually is broken: need to update this makefile.]

OBJS = gpio.o gpio-pud.o uart.o kmalloc.o
# gpio-int.o interrupts-c.o interrupts-asm.o
#  uart.o

ifndef CS140E_PATH
$(error CS140E_PATH is not set: this should contain the absolute path to where this directory is.  Define it in your shell's initialiation.  For example, .tcshrc for tcsh or .bashrc for bash)
endif

# useful set of defines.
include $(CS140E_PATH)/libpi/includes.mk

START = $(LPP)/cs140e-start.o
MEMMAP = $(LPP)/memmap

CFLAGS += -Wstack-usage=512 -Wno-unused-function -Wno-unused-variable
CFLAGS += -Werror
# $(OBJS)

all:  $(OBJS)

# pull in dependency info for *existing* .o files
-include $(OBJS:.o=.d)

# should re-do this to use the libpi makefile.

# compile and generate dependency info;
# more complicated dependency computation, so all prereqs listed
# will also become command-less, prereq-less targets
#   sed:    strip the target (everything before colon)
#   sed:    remove any continuation backslashes
#   fmt -1: list words one per line
#   sed:    strip leading spaces
#   sed:    add trailing colons
%.o: %.c  Makefile
	$(CC) -c $(CFLAGS) $*.c -o $*.o
	$(CC) -MM $(CFLAGS) $*.c > $*.d
	@mv -f $*.d $*.d.tmp
	@sed -e 's|.*:|$*.o:|' < $*.d.tmp > $*.d
	@sed -e 's/.*://' -e 's/\\$$//' < $*.d.tmp | fmt -1 | \
	  sed -e 's/^ *//' -e 's/$$/:/' >> $*.d
	@rm -f $*.d.tmp

.s.o: Makefile
	$(AS) $(ASFLAGS) $< -o $@

.S.o: Makefile
	$(CC) -c $(CPP_ASFLAGS) $< -o $@

run:
	my-install $(NAME).bin

tags:
	@rm -f tags
	ctags *.[chsS] $(CS140E_LIBPI_PATH)/*.[chsS]

# remove compilation products
clean:
	rm -f replay $(OBJS) *.d *.bin *.elf *.list *.img Makefile.bak *~ tags

.PHONY: run libpi tags clean
