PROGS =  0-example-bitops.c

# swap these if your bootloader doesn't work.
BOOTLOADER = my-install
BOOTLOADER = pi-install

# set to 1 if you want to run.
RUN=1

include $(CS140E_2025_PATH)/libpi/mk/Makefile.template-fixed
